version: '2'
services:
  fog-pxe:
    image: fog-pxe
    name: fog-pxe-server
    mem_limit: 1024M
    networks:
      - bridge

    entrypoint: '/bin/bash'
    stdin_open: true
    tty: true

networks:
    bridge:
      external:
        name: macvlan
